spring:
  application:
    name: montador-de-rpg-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/rpgdb
    username: rpguser
    password: rpgpass
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
