spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/db_rpg
    username: rpguser
    password: rpgpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ID.apps.googleusercontent.com
            client-secret: SECRET
            scope:
              - profile
              - email

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,https://*.githubpreview.dev,https://*.app.github.dev}